export default [
  'ADD ARTICLE', 'REMOVE ARTICLE', 'UPDATE ARTICLE', 'ADD ARTICLE AND STOCK', 'ADD ARTICLE AND SALE',
  'ADD SALE', 'ADD STOCK', 'REMOVE STOCK', 'REMOVE SALE', 'INCORRECT PRICE', 'REMOVE PRICE',
  'ADD PRICE', 'ADD UPDATE ARTICLE', 'DESIGNATION EXIST ERROR', 'FILE ERROR',
]